# Generated by Django 4.2 on 2023-05-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sepal_width', models.DecimalField(decimal_places=1, max_digits=4)),
                ('petal_length', models.DecimalField(decimal_places=1, max_digits=4)),
                ('petal_width', models.DecimalField(decimal_places=1, max_digits=4)),
                ('species', models.CharField(max_length=50)),
            ],
        ),
    ]
